Repository BookStackApp/BookStack, pull requests merged in 2018-12, with the labels that each got.

#1180 Updates for PL language
  resources/lang/pl/activities.php
  resources/lang/pl/auth.php
  resources/lang/pl/common.php
  resources/lang/pl/components.php
  resources/lang/pl/entities.php
  resources/lang/pl/errors.php
  resources/lang/pl/passwords.php
  resources/lang/pl/settings.php
Labels: :earth_africa: Translations

#1183 Add Ukrainian translate
  config/app.php
  resources/lang/en/settings.php
  resources/lang/uk/activities.php
  resources/lang/uk/auth.php
  resources/lang/uk/common.php
  resources/lang/uk/components.php
  resources/lang/uk/entities.php
  resources/lang/uk/errors.php
  resources/lang/uk/pagination.php
  resources/lang/uk/passwords.php
  resources/lang/uk/settings.php
  resources/lang/uk/validation.php
Labels: :earth_africa: Translations

#1133 Adds a default timeout of 60 seconds to dropzone.
  resources/assets/js/vues/components/dropzone.js
  resources/lang/ar/errors.php
  resources/lang/de/errors.php
  resources/lang/en/errors.php
  resources/lang/es/errors.php
  resources/lang/es_AR/errors.php
  resources/lang/fr/errors.php
  resources/lang/it/errors.php
  resources/lang/ja/errors.php
  resources/lang/kr/errors.php
  resources/lang/nl/errors.php
  resources/lang/pl/errors.php
  resources/lang/pt_BR/errors.php
  resources/lang/ru/errors.php
  resources/lang/sk/errors.php
  resources/lang/sv/errors.php
  resources/lang/zh_CN/errors.php
  resources/lang/zh_TW/errors.php
Labels: Enhancement, Front-End

#1096 Add option to disable LDAPS Certificate Validation
  .env.example
  app/Auth/Access/LdapService.php
  config/services.php
Labels: Back-End, Enhancement
