Repository BookStackApp/BookStack, pull requests merged in 2018-07, with the labels that each got.

#874 Fixes undefined error when clicking on link under page navigation.
  resources/assets/js/components/page-display.js
Labels: Bug

#906 Fixes issue with code not wrapping on revision page.
  resources/assets/sass/_pages.scss
  resources/views/pages/revision.blade.php
Labels: Bug

#907 Changes the way the date is displayed in image-manager.
  resources/assets/js/services/dates.js
  resources/assets/js/vues/image-manager.js
Labels: Enhancement

#918 Adds missing pt_BR strings
  resources/lang/pt_BR/common.php
Labels: Translations

#925 Fixed German translations for notifications
  resources/lang/de/activities.php
Labels: Translations

#933 French translation update
  resources/lang/fr/activities.php
  resources/lang/fr/auth.php
  resources/lang/fr/common.php
  resources/lang/fr/components.php
  resources/lang/fr/entities.php
  resources/lang/fr/errors.php
  resources/lang/fr/settings.php
Labels: Translations

#904 add everything needed to use discord as social login provider
  .env.example
  app/Providers/EventServiceProvider.php
  app/Services/SocialAuthService.php
  composer.json
  composer.lock
  config/services.php
  resources/assets/icons/auth/discord.svg
Labels: Documentation Update, Enhancement
