Repository BookStackApp/BookStack, pull requests merged in 2018-09, with the labels that each got.

#1008 #784 - Adds ability to remove particular revision.
  app/Http/Controllers/PageController.php
  app/Page.php
  resources/assets/sass/_lists.scss
  resources/assets/sass/_tables.scss
  resources/lang/de/entities.php
  resources/lang/en/entities.php
  resources/lang/es/entities.php
  resources/lang/es_AR/entities.php
  resources/lang/fr/entities.php
  resources/lang/it/entities.php
  resources/lang/ja/entities.php
  resources/lang/nl/entities.php
  resources/lang/pl/entities.php
  resources/lang/pt_BR/entities.php
  resources/lang/ru/entities.php
  resources/lang/sk/entities.php
  resources/lang/sv/entities.php
  resources/lang/zh_CN/entities.php
  resources/lang/zh_TW/entities.php
  resources/views/pages/revisions.blade.php
  resources/views/partials/custom-styles.blade.php
  routes/web.php
  tests/Entity/PageRevisionTest.php
Labels: Enhancement

#986 Adds and fixes pt_BR strings
  resources/lang/pt_BR/components.php
  resources/lang/pt_BR/entities.php
  resources/lang/pt_BR/errors.php
  resources/lang/pt_BR/settings.php
Labels: Translations

#1009 Fixes issue wth the dropdown list upon double clicking.
  resources/assets/js/components/chapter-toggle.js
  resources/assets/sass/_lists.scss
Labels: Bug

#983 Update german translation
  resources/lang/de/settings.php
Labels: Translations

#1021 Spanish translation
  resources/lang/es/activities.php
  resources/lang/es/common.php
  resources/lang/es/entities.php
  resources/lang/es/errors.php
  resources/lang/es/settings.php
Labels: Translations

#1026 Update german translation
  resources/lang/de/settings.php
Labels: Translations
