Repository BookStackApp/BookStack, pull requests merged in 2019-10, with the labels that each got.

#1698 Fixing composer install inside docker `app` container
  dev/docker/Dockerfile
Labels: :wrench: Maintenance

#1646 Update settings.php
  resources/lang/ru/settings.php
Labels: :earth_africa: Translations

#1681 Updated 'Spanish Argentina' translation.
  resources/lang/es_AR/validation.php
Labels: :earth_africa: Translations

#1695 French translation update
  resources/lang/fr/auth.php
  resources/lang/fr/common.php
  resources/lang/fr/entities.php
  resources/lang/fr/errors.php
  resources/lang/fr/passwords.php
  resources/lang/fr/settings.php
  resources/lang/fr/validation.php
Labels: :earth_africa: Translations

#1462 Update maintenance.php to link to Github release page & minor style tweak
  resources/views/settings/maintenance.blade.php
Labels: :computer: Front-End, :hammer_and_wrench: Enhancement

#1687 Fix Book form (create) returning to the full books list on cancel
  resources/views/books/form.blade.php
  tests/Entity/EntityTest.php
Labels: :hammer_and_wrench: Enhancement, :massage: UX

#1746 Bugfix - download and assign avatar when creating LDAP user in database
  app/Http/Controllers/Auth/LoginController.php
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement
