Repository BookStackApp/BookStack, pull requests merged in 2019-12, with the labels that each got.

#1734 Update Korean translation
  .gitignore
  resources/lang/ko/activities.php
  resources/lang/ko/auth.php
  resources/lang/ko/common.php
  resources/lang/ko/components.php
  resources/lang/ko/entities.php
  resources/lang/ko/errors.php
  resources/lang/ko/passwords.php
  resources/lang/ko/settings.php
  resources/lang/ko/validation.php
Labels: :earth_africa: Translations

#1762 Update Italian translation
  resources/lang/it/entities.php
  resources/lang/it/errors.php
  resources/lang/it/settings.php
Labels: :earth_africa: Translations

#1791 Simplified Chinese Translation Update
  resources/lang/zh_CN/auth.php
  resources/lang/zh_CN/common.php
  resources/lang/zh_CN/entities.php
  resources/lang/zh_CN/errors.php
  resources/lang/zh_CN/settings.php
  resources/lang/zh_CN/validation.php
Labels: :earth_africa: Translations

#1804 Update of polish language
  resources/lang/pl/activities.php
  resources/lang/pl/auth.php
  resources/lang/pl/common.php
  resources/lang/pl/components.php
  resources/lang/pl/entities.php
  resources/lang/pl/errors.php
  resources/lang/pl/settings.php
  resources/lang/pl/validation.php
Labels: :earth_africa: Translations

#1819 update translation
  resources/lang/zh_TW/entities.php
Labels: :earth_africa: Translations

#1797 Modify Chinese language pack
  resources/lang/zh_CN/auth.php
  resources/lang/zh_CN/common.php
  resources/lang/zh_CN/entities.php
  resources/lang/zh_CN/errors.php
  resources/lang/zh_CN/settings.php
  resources/lang/zh_CN/validation.php
Labels: :earth_africa: Translations

#1793 Fix An Exception
  app/Http/Middleware/TrustProxies.php
Labels: :bug: Bug

#1730 Added support for Pascal language
  resources/assets/js/services/code.js
  resources/views/components/code-editor.blade.php
Labels: :computer: Front-End, :hammer_and_wrench: Enhancement
