Repository BookStackApp/BookStack, pull requests merged in 2019-01, with the labels that each got.

#1197 Spanish update
  resources/lang/es/activities.php
  resources/lang/es/auth.php
  resources/lang/es/common.php
  resources/lang/es/components.php
  resources/lang/es/entities.php
  resources/lang/es/errors.php
  resources/lang/es/pagination.php
  resources/lang/es/passwords.php
  resources/lang/es/settings.php
  resources/lang/es/validation.php
Labels: :earth_africa: Translations

#1205 Simplified example env and created full example copy
  .env.example
  .env.example.complete
  config/app.php
  config/session.php
Labels: :book: Docs Update, :wrench: Maintenance, UX

#1237 PHPCS related fixes.
  app/Auth/Access/LdapService.php
  app/Auth/Permissions/PermissionService.php
  app/Entities/EntityProvider.php
  app/Entities/Repos/PageRepo.php
  app/Exceptions/HttpFetchException.php
  app/Exceptions/UserUpdateException.php
  app/Notifications/MailNotification.php
  app/Notifications/ResetPassword.php
  app/Providers/TranslationServiceProvider.php
  app/Translation/Translator.php
  app/Uploads/HttpFetcher.php
Labels: :wrench: Maintenance
