Repository BookStackApp/BookStack, pull requests merged in 2019-03, with the labels that each got.

#1263 Add Powershell Code Markup
  resources/views/components/code-editor.blade.php
Labels: :computer: Front-End, :hammer_and_wrench: Enhancement

#1314 Update Dutch password_hint translation to correspond with validation
  resources/lang/nl/auth.php
Labels: :earth_africa: Translations

#1272 Add german translations for shelves
  resources/lang/de/entities.php
  resources/lang/de_informal/entities.php
Labels: :earth_africa: Translations

#1238 Fixes tooltip on the image manager.
  resources/assets/sass/_components.scss
  resources/lang/en/validation.php
Labels: :bug: Bug, :computer: Front-End

#1327 Updated 'Spanish Argentina' translation.
  resources/lang/es_AR/errors.php
  resources/lang/es_AR/validation.php
Labels: :earth_africa: Translations

#1347 Czech translation
  config/app.php
  resources/lang/cs/activities.php
  resources/lang/cs/auth.php
  resources/lang/cs/common.php
  resources/lang/cs/components.php
  resources/lang/cs/entities.php
  resources/lang/cs/errors.php
  resources/lang/cs/pagination.php
  resources/lang/cs/passwords.php
  resources/lang/cs/settings.php
  resources/lang/cs/validation.php
  resources/lang/en/settings.php
Labels: :earth_africa: Translations
