Repository BookStackApp/BookStack, pull requests merged in 2020-09, with the labels that each got.

#2274 Fixed "Ubunto Mono" $mono type misspelling
  resources/sass/_variables.scss
Labels: :bug: Bug, :computer: Front-End

#2268 Fix the `AddActivityIndexes` migration's `down()` method
  database/migrations/2020_09_19_094251_add_activity_indexes.php
Labels: :bug: Bug, :cd: Database, :factory: Back-End

#2270 Add `test-migrations` workflow
  .github/workflows/test-migrations.yml
Labels: :octocat: Admin/Meta, :wrench: Maintenance

#2262 New Crowdin updates
  resources/lang/cs/auth.php
  resources/lang/cs/common.php
  resources/lang/cs/components.php
  resources/lang/cs/entities.php
  resources/lang/cs/errors.php
  resources/lang/cs/settings.php
  resources/lang/cs/validation.php
  resources/lang/de/entities.php
  resources/lang/de/settings.php
  resources/lang/de_informal/entities.php
  resources/lang/de_informal/settings.php
  resources/lang/es_AR/entities.php
  resources/lang/ru/entities.php
  resources/lang/ru/settings.php
  resources/lang/zh_CN/entities.php
  resources/lang/zh_CN/settings.php
Labels: :earth_africa: Translations

#2272 Fixed canonical redirects on non-root url app instances
  public/.htaccess
Labels: :factory: Back-End, :wrench: Maintenance
