Repository BookStackApp/BookStack, pull requests merged in 2020-02, with the labels that each got.

#1866 Auth service alignment
  .env.example.complete
  app/Auth/Access/ExternalAuthService.php
  app/Auth/Access/ExternalBaseUserProvider.php
  app/Auth/Access/Guards/ExternalBaseSessionGuard.php
  app/Auth/Access/Guards/LdapSessionGuard.php
  app/Auth/Access/Guards/Saml2SessionGuard.php
  app/Auth/Access/LdapService.php
  app/Auth/Access/RegistrationService.php
  app/Auth/Access/Saml2Service.php
  app/Auth/Access/SocialAuthService.php
  app/Auth/User.php
  app/Auth/UserRepo.php
  app/Config/auth.php
  app/Config/saml2.php
  app/Exceptions/AuthException.php
  app/Exceptions/Handler.php
  app/Exceptions/LoginAttemptEmailNeededException.php
  app/Exceptions/LoginAttemptException.php
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/Auth/Saml2Controller.php
  app/Http/Controllers/Auth/SocialController.php
  app/Http/Controllers/Auth/UserInviteController.php
  app/Http/Controllers/SettingController.php
  app/Http/Kernel.php
  app/Http/Middleware/CheckGuard.php
  app/Http/Middleware/PermissionMiddleware.php
  app/Providers/AuthServiceProvider.php
  resources/lang/en/errors.php
  resources/lang/en/settings.php
  resources/views/auth/forms/login/ldap.blade.php
  resources/views/auth/forms/login/saml2.blade.php
  resources/views/auth/forms/login/standard.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/common/header.blade.php
  resources/views/settings/index.blade.php
  resources/views/settings/roles/form.blade.php
  resources/views/users/form.blade.php
  routes/web.php
  tests/Api/ApiAuthTest.php
  tests/Auth/LdapTest.php
  tests/Auth/Saml2Test.php
  tests/SharedTestHelpers.php
  tests/TestCase.php
Labels: :door: Authentication, :rocket: Priority

#1850 New Crowdin translations
  resources/lang/ar/errors.php
  resources/lang/ar/settings.php
  resources/lang/cs/errors.php
  resources/lang/cs/settings.php
  resources/lang/da/errors.php
  resources/lang/da/settings.php
  resources/lang/de/errors.php
  resources/lang/de/settings.php
  resources/lang/de_informal/errors.php
  resources/lang/de_informal/settings.php
  resources/lang/es/errors.php
  resources/lang/es/settings.php
  resources/lang/es_AR/errors.php
  resources/lang/es_AR/settings.php
  resources/lang/fr/errors.php
  resources/lang/fr/settings.php
  resources/lang/hu/common.php
  resources/lang/hu/errors.php
  resources/lang/hu/settings.php
  resources/lang/hu/validation.php
  resources/lang/it/errors.php
  resources/lang/it/settings.php
  resources/lang/ja/errors.php
  resources/lang/ja/settings.php
  resources/lang/ko/errors.php
  resources/lang/ko/settings.php
  resources/lang/nl/common.php
  resources/lang/nl/errors.php
  resources/lang/nl/settings.php
  resources/lang/pl/errors.php
  resources/lang/pl/settings.php
  resources/lang/pt_BR/errors.php
  resources/lang/pt_BR/settings.php
  resources/lang/ru/errors.php
  resources/lang/ru/settings.php
  resources/lang/sk/errors.php
  resources/lang/sk/settings.php
  resources/lang/sv/errors.php
  resources/lang/sv/settings.php
  resources/lang/tr/errors.php
  resources/lang/tr/settings.php
  resources/lang/uk/errors.php
  resources/lang/uk/settings.php
  resources/lang/zh_CN/errors.php
  resources/lang/zh_CN/settings.php
  resources/lang/zh_TW/auth.php
  resources/lang/zh_TW/common.php
  resources/lang/zh_TW/entities.php
  resources/lang/zh_TW/errors.php
  resources/lang/zh_TW/settings.php
  resources/lang/zh_TW/validation.php
Labels: :earth_africa: Translations

#1899 Fix for missing cover on create new shelf
  app/Http/Controllers/BookshelfController.php
Labels: :bug: Bug, :factory: Back-End
