Repository BookStackApp/BookStack, pull requests merged in 2020-10, with the labels that each got.

#2303 New Crowdin updates
  resources/lang/es/settings.php
  resources/lang/zh_CN/settings.php
Labels: :earth_africa: Translations, hacktoberfest-accepted

#2302 Add VBScript Codemirror
  resources/js/services/code.js
  resources/views/components/code-editor.blade.php
Labels: hacktoberfest-accepted

#2296 Fix build:js:watch not building at first launch in Docker
  dev/docker/entrypoint.node.sh
  package.json
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement, :wrench: Maintenance, hacktoberfest-accepted

#2298 Install composer dependencies in Docker entrypoint
  dev/docker/entrypoint.app.sh
  readme.md
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement, :octocat: Admin/Meta, hacktoberfest-accepted

#2328 Fixes from laravel-microscope package
  app/Auth/Permissions/PermissionService.php
  app/Http/Controllers/Images/ImageController.php
  composer.json
  tests/Permissions/RestrictionsTest.php
  tests/User/UserApiTokenTest.php
  tests/User/UserPreferencesTest.php
  tests/User/UserProfileTest.php
Labels: hacktoberfest-accepted
