Repository BookStackApp/BookStack, pull requests merged in 2020-03, with the labels that each got.

#1827 Hebrew Translation
  app/Config/app.php
  app/Http/Middleware/Localization.php
  resources/lang/he/activities.php
  resources/lang/he/auth.php
  resources/lang/he/common.php
  resources/lang/he/components.php
  resources/lang/he/entities.php
  resources/lang/he/errors.php
  resources/lang/he/pagination.php
  resources/lang/he/passwords.php
  resources/lang/he/settings.php
  resources/lang/he/validation.php
Labels: :earth_africa: Translations

#1878 Added support for Fortran language
  resources/js/services/code.js
  resources/views/components/code-editor.blade.php
Labels: :hammer_and_wrench: Enhancement, :memo: WYSIWYG Editor, > Markdown Editor

#1851 Add Perl syntax highlighting to code editor
  resources/js/services/code.js
  resources/views/components/code-editor.blade.php
Labels: :hammer_and_wrench: Enhancement, :memo: WYSIWYG Editor, > Markdown Editor

#1889 Fixed 'interaction_required' response for azure
  app/Auth/Access/SocialAuthService.php
Labels: :bug: Bug, :door: Authentication, :hammer_and_wrench: Enhancement

#1943 Removed spacing in color picker actions to account for languages with longer text
  resources/views/components/setting-entity-color-picker.blade.php
Labels: :art: Design, :computer: Front-End, :hammer_and_wrench: Enhancement

#1942 Updated login and registration header actions to be consistent with other header links
  resources/views/common/header.blade.php
Labels: :art: Design, :hammer_and_wrench: Enhancement

#1900 Validation fixes
  app/Http/Controllers/BookController.php
  app/Http/Controllers/BookshelfController.php
  app/Http/Controllers/Images/GalleryImageController.php
  app/Http/Controllers/SettingController.php
  app/Http/Controllers/UserController.php
  app/Uploads/ImageRepo.php
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement
