Repository BookStackApp/BookStack, pull requests merged in 2021-02, with the labels that each got.

#2530 Update TrashCan.php
  app/Entities/Tools/TrashCan.php
Labels: :factory: Back-End

#2376 LDAP: Added TLS support
  .env.example.complete
  app/Auth/Access/LdapService.php
  app/Config/services.php
Labels: :door: Authentication

#2591 Adding APP_VIEWS_BOOKSHELF to .ENV
  .env.example.complete
  app/Config/setting-defaults.php
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement
