Repository BookStackApp/BookStack, pull requests merged in 2021-01, with the labels that each got.

#2436 Entity Ownership System
  app/Actions/Comment.php
  app/Auth/Permissions/PermissionService.php
  app/Auth/UserRepo.php
  app/Entities/EntityProvider.php
  app/Entities/Models/Entity.php
  app/Entities/Repos/BaseRepo.php
  app/Entities/Repos/BookRepo.php
  app/Entities/Repos/BookshelfRepo.php
  app/Entities/Repos/ChapterRepo.php
  app/Entities/Repos/PageRepo.php
  app/Entities/Tools/PermissionsUpdater.php
  app/Http/Controllers/BookController.php
  app/Http/Controllers/BookshelfController.php
  app/Http/Controllers/ChapterController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/PageController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/UserSearchController.php
  app/Traits/HasCreatorAndUpdater.php
  app/Traits/HasOwner.php
  app/Uploads/Attachment.php
  app/Uploads/Image.php
  app/helpers.php
  database/migrations/2020_12_30_173528_add_owned_by_field_to_entities.php
  database/seeds/DummyContentSeeder.php
  resources/js/components/breadcrumb-listing.js
  resources/js/components/dropdown-search.js
  resources/js/components/dropdown.js
  resources/js/components/index.js
  resources/js/components/user-select.js
  resources/lang/en/entities.php
  resources/lang/en/settings.php
  resources/sass/_components.scss
  resources/sass/_header.scss
  resources/sass/_layout.scss
  resources/views/components/user-select-list.blade.php
  resources/views/components/user-select.blade.php
  resources/views/form/entity-permissions.blade.php
  resources/views/partials/breadcrumb-listing.blade.php
  resources/views/partials/entity-meta.blade.php
  resources/views/users/delete.blade.php
  routes/web.php
  tests/BrowserKitTest.php
  tests/Entity/SortTest.php
  tests/Permissions/EntityOwnerChangeTest.php
  tests/Permissions/RolesTest.php
  tests/User/UserManagementTest.php
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement

#2416 Fix issue with viewing export dropdown list
  resources/sass/_layout.scss
Labels: :art: Design

#2336 Added Norwegian translation to BookStack
  app/Config/app.php
  app/Http/Middleware/Localization.php
  resources/lang/en/settings.php
  resources/lang/no_NB/activities.php
  resources/lang/no_NB/auth.php
  resources/lang/no_NB/common.php
  resources/lang/no_NB/components.php
  resources/lang/no_NB/entities.php
  resources/lang/no_NB/errors.php
  resources/lang/no_NB/pagination.php
  resources/lang/no_NB/passwords.php
  resources/lang/no_NB/settings.php
  resources/lang/no_NB/validation.php
Labels: :earth_africa: Translations

#2439 New Crowdin updates
  resources/lang/es/entities.php
  resources/lang/nb/activities.php
  resources/lang/nb/common.php
  resources/lang/nb/entities.php
  resources/lang/nb/settings.php
  resources/lang/nb/validation.php
Labels: :earth_africa: Translations

#2441 New Crowdin updates
  resources/lang/es_AR/entities.php
  resources/lang/fr/entities.php
  resources/lang/fr/settings.php
  resources/lang/zh_CN/entities.php
  resources/lang/zh_CN/settings.php
Labels: :earth_africa: Translations

#2464 New Crowdin updates
  resources/lang/it/settings.php
  resources/lang/ru/activities.php
  resources/lang/ru/entities.php
  resources/lang/ru/settings.php
  resources/lang/zh_TW/entities.php
Labels: :earth_africa: Translations

#2469 New Crowdin updates
  resources/lang/tr/activities.php
  resources/lang/tr/entities.php
  resources/lang/tr/settings.php
  resources/lang/tr/validation.php
Labels: :earth_africa: Translations

#2482 New Crowdin updates
  resources/lang/zh_TW/activities.php
  resources/lang/zh_TW/entities.php
  resources/lang/zh_TW/settings.php
Labels: :earth_africa: Translations

#2484 Disable autocomplete on the change password field
  resources/views/form/password.blade.php
  resources/views/users/form.blade.php
Labels: :computer: Front-End, :hammer_and_wrench: Enhancement, :massage: UX

#2510 Docker: Fix permission with node service by adding node as user
  docker-compose.yml
Labels: :wrench: Maintenance
