Repository BookStackApp/BookStack, pull requests merged in 2021-06, with the labels that each got.

#2784 Adding Croatian language
  resources/lang/hr/activities.php
  resources/lang/hr/auth.php
  resources/lang/hr/common.php
  resources/lang/hr/components.php
  resources/lang/hr/entities.php
  resources/lang/hr/errors.php
  resources/lang/hr/pagination.php
  resources/lang/hr/passwords.php
  resources/lang/hr/settings.php
  resources/lang/hr/validation.php
Labels: :earth_africa: Translations

#2785 Roll-out and re-fix of croation via crowdin
  resources/lang/ar/settings.php
  resources/lang/bg/settings.php
  resources/lang/bs/settings.php
  resources/lang/ca/settings.php
  resources/lang/cs/settings.php
  resources/lang/da/settings.php
  resources/lang/de/settings.php
  resources/lang/de_informal/activities.php
  resources/lang/de_informal/entities.php
  resources/lang/de_informal/errors.php
  resources/lang/de_informal/settings.php
  resources/lang/es/settings.php
  resources/lang/es_AR/settings.php
  resources/lang/fa/settings.php
  resources/lang/fr/settings.php
  resources/lang/he/settings.php
  resources/lang/hr/activities.php
  resources/lang/hr/auth.php
  resources/lang/hr/common.php
  resources/lang/hr/entities.php
  resources/lang/hr/errors.php
  resources/lang/hr/passwords.php
  resources/lang/hr/settings.php
  resources/lang/hu/settings.php
  resources/lang/id/settings.php
  resources/lang/it/settings.php
  resources/lang/ja/settings.php
  resources/lang/ko/settings.php
  resources/lang/ko/validation.php
  resources/lang/lv/settings.php
  resources/lang/nb/settings.php
  resources/lang/nl/settings.php
  resources/lang/pl/settings.php
  resources/lang/pt/settings.php
  resources/lang/pt_BR/settings.php
  resources/lang/ru/settings.php
  resources/lang/sk/settings.php
  resources/lang/sl/settings.php
  resources/lang/sv/settings.php
  resources/lang/tr/settings.php
  resources/lang/uk/settings.php
  resources/lang/vi/settings.php
  resources/lang/zh_CN/settings.php
  resources/lang/zh_TW/settings.php
Labels: :earth_africa: Translations

#2787 New Crowdin updates
  resources/lang/de/common.php
  resources/lang/nl/common.php
Labels: :earth_africa: Translations

#2791 Attachment serving without forced download
  app/Http/Controllers/AttachmentController.php
  app/Http/Controllers/Controller.php
  app/Uploads/Attachment.php
  app/Uploads/AttachmentService.php
  composer.json
  resources/js/components/attachments-list.js
  resources/js/components/index.js
  resources/views/attachments/list.blade.php
  tests/Uploads/AttachmentTest.php
Labels: :factory: Back-End, :hammer: Feature Request

#2790 New Crowdin updates
  resources/lang/es_AR/settings.php
  resources/lang/id/common.php
  resources/lang/id/entities.php
  resources/lang/id/errors.php
  resources/lang/id/settings.php
  resources/lang/id/validation.php
  resources/lang/zh_CN/auth.php
Labels: :earth_africa: Translations

#2393 Create content meta tags for Shelf, Book, Chapter, and Page
  app/Entities/Models/Page.php
  app/Entities/Tools/PageContent.php
  resources/views/base.blade.php
  resources/views/books/show.blade.php
  resources/views/chapters/show.blade.php
  resources/views/pages/show.blade.php
  resources/views/shelves/show.blade.php
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement
