Repository BookStackApp/BookStack, pull requests merged in 2021-05, with the labels that each got.

#1998 Add support Windows Authentication via SAML
  .env.example.complete
  app/Config/saml2.php
Labels: :book: Docs Update, :door: Authentication

#2719 New Crowdin updates
  resources/lang/ar/common.php
  resources/lang/ar/entities.php
  resources/lang/id/common.php
  resources/lang/it/components.php
  resources/lang/it/entities.php
  resources/lang/it/errors.php
  resources/lang/it/passwords.php
  resources/lang/it/settings.php
  resources/lang/it/validation.php
  resources/lang/nl/entities.php
  resources/lang/pt/common.php
Labels: :earth_africa: Translations

#2716 Update Korean translation
  resources/lang/ko/activities.php
  resources/lang/ko/common.php
  resources/lang/ko/entities.php
  resources/lang/ko/settings.php
  resources/lang/ko/validation.php
Labels: :earth_africa: Translations

#2737 New Crowdin updates
  resources/lang/ar/activities.php
  resources/lang/ar/auth.php
  resources/lang/ar/components.php
  resources/lang/ar/entities.php
  resources/lang/ar/errors.php
  resources/lang/bg/errors.php
  resources/lang/bs/errors.php
  resources/lang/ca/errors.php
  resources/lang/cs/errors.php
  resources/lang/da/errors.php
  resources/lang/de/errors.php
  resources/lang/de_informal/errors.php
  resources/lang/es/errors.php
  resources/lang/es_AR/common.php
  resources/lang/es_AR/entities.php
  resources/lang/es_AR/errors.php
  resources/lang/fa/errors.php
  resources/lang/fr/common.php
  resources/lang/fr/errors.php
  resources/lang/he/errors.php
  resources/lang/hu/errors.php
  resources/lang/id/errors.php
  resources/lang/it/errors.php
  resources/lang/ja/errors.php
  resources/lang/ko/errors.php
  resources/lang/lv/errors.php
  resources/lang/nb/errors.php
  resources/lang/nl/errors.php
  resources/lang/pl/errors.php
  resources/lang/pt/common.php
  resources/lang/pt/errors.php
  resources/lang/pt_BR/errors.php
  resources/lang/ru/errors.php
  resources/lang/sk/errors.php
  resources/lang/sl/errors.php
  resources/lang/sv/errors.php
  resources/lang/tr/errors.php
  resources/lang/uk/errors.php
  resources/lang/vi/errors.php
  resources/lang/zh_CN/errors.php
  resources/lang/zh_TW/errors.php
Labels: :earth_africa: Translations

#2748 Favourite System
  app/Actions/Favourite.php
  app/Actions/View.php
  app/Actions/ViewService.php
  app/Auth/Permissions/PermissionService.php
  app/Auth/User.php
  app/Auth/UserRepo.php
  app/Config/app.php
  app/Console/Commands/ClearViews.php
  app/Entities/Models/Entity.php
  app/Entities/Queries/EntityQuery.php
  app/Entities/Queries/Popular.php
  app/Entities/Queries/RecentlyViewed.php
  app/Entities/Queries/TopFavourites.php
  app/Entities/Tools/TrashCan.php
  app/Facades/Views.php
  app/Http/Controllers/BookController.php
  app/Http/Controllers/BookshelfController.php
  app/Http/Controllers/ChapterController.php
  app/Http/Controllers/FavouriteController.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/PageController.php
  app/Http/Controllers/SearchController.php
  app/Interfaces/Favouritable.php
  app/Interfaces/Viewable.php
  app/Providers/CustomFacadeProvider.php
  database/migrations/2021_05_15_173110_create_favourites_table.php
  resources/icons/star-circle.svg
  resources/icons/star-outline.svg
  resources/lang/en/activities.php
  resources/lang/en/common.php
  resources/lang/en/entities.php
  resources/views/books/show.blade.php
  resources/views/chapters/show.blade.php
  resources/views/common/detailed-listing-paginated.blade.php
  resources/views/common/detailed-listing-with-more.blade.php
  resources/views/common/header.blade.php
  resources/views/common/home-sidebar.blade.php
  resources/views/common/home.blade.php
  resources/views/errors/404.blade.php
  resources/views/pages/show.blade.php
  resources/views/partials/entity-favourite-action.blade.php
  resources/views/shelves/show.blade.php
  routes/web.php
  tests/FavouriteTest.php
Labels: :hammer: Feature Request, :hammer_and_wrench: Enhancement

#2320 Import thumbnail photos when LDAP users are created.
  app/Auth/Access/Guards/LdapSessionGuard.php
  app/Auth/Access/LdapService.php
  app/Config/services.php
Labels: hacktoberfest-accepted

#2768 [sec] Fixes a few minor vulnerabilies when using target="_blank" on links (RSPEC-5148)
  resources/views/api-docs/index.blade.php
  resources/views/attachments/manager-list.blade.php
  resources/views/common/footer.blade.php
  resources/views/components/image-manager-form.blade.php
  resources/views/components/page-picker.blade.php
  resources/views/pages/revisions.blade.php
  resources/views/partials/entity-export-menu.blade.php
Labels: :hammer_and_wrench: Enhancement, :lock: Security

#2511 Add prev and next button to navigate through different pages
  app/Entities/Models/Page.php
  app/Entities/Repos/PageRepo.php
  app/Http/Controllers/PageController.php
  resources/sass/_layout.scss
  resources/sass/_text.scss
  resources/views/pages/show.blade.php
Labels: :factory: Back-End, :hammer: Feature Request, :massage: UX
