Repository BookStackApp/BookStack, pull requests merged in 2021-11, with the labels that each got.

#3023 New Crowdin updates
  resources/lang/lv/settings.php
  resources/lang/nl/activities.php
  resources/lang/nl/auth.php
  resources/lang/nl/common.php
  resources/lang/nl/entities.php
  resources/lang/pl/errors.php
Labels: :earth_africa: Translations

#3032 Modernize third party services' logos
  resources/icons/auth/facebook.svg
  resources/icons/auth/slack.svg
Labels: :hammer_and_wrench: Enhancement, :art: Design

#3042 Tag view
  app/Actions/TagRepo.php
  app/Http/Controllers/TagController.php
  resources/icons/info-filled.svg
  resources/icons/leaderboard.svg
  resources/lang/en/common.php
  resources/lang/en/entities.php
  resources/sass/_blocks.scss
  resources/sass/_tables.scss
  resources/views/books/index.blade.php
  resources/views/entities/tag-list.blade.php
  resources/views/entities/tag-manager.blade.php
  resources/views/entities/tag.blade.php
  resources/views/form/request-query-inputs.blade.php
  resources/views/shelves/index.blade.php
  resources/views/tags/index.blade.php
  resources/views/tags/parts/table-row.blade.php
  routes/web.php
  tests/Entity/TagTest.php
  tests/TestResponse.php
Labels: :hammer_and_wrench: Enhancement

#3043 Search Engine Improvement
  app/Actions/Tag.php
  app/Console/Commands/RegenerateSearch.php
  app/Entities/Models/Book.php
  app/Entities/Models/Bookshelf.php
  app/Entities/Models/Chapter.php
  app/Entities/Models/Entity.php
  app/Entities/Models/Page.php
  app/Entities/Repos/PageRepo.php
  app/Entities/Tools/SearchIndex.php
  app/Entities/Tools/SearchOptions.php
  app/Entities/Tools/SearchResultsFormatter.php
  app/Entities/Tools/SearchRunner.php
  app/Http/Controllers/SearchController.php
  database/seeders/LargeContentSeeder.php
  resources/sass/_blocks.scss
  resources/views/entities/list-item-basic.blade.php
  resources/views/entities/list-item.blade.php
  resources/views/entities/tag.blade.php
  tests/Entity/EntitySearchTest.php
Labels: :hammer_and_wrench: Enhancement, :book: Docs Update, :cd: Database, :factory: Back-End

#3068 Set taborder for TOTP Verification
  resources/views/mfa/parts/verify-totp.blade.php
Labels: :hammer_and_wrench: Enhancement, :massage: UX

#3069 feat(PageContent): set unique ids on nested headers
  app/Entities/Tools/PageContent.php
  tests/Entity/PageContentTest.php
Labels: :bug: Bug, :factory: Back-End

#3072 Support custom commands via logical theme system
  app/Theming/ThemeService.php
  dev/docs/logical-theme-system.md
  tests/ThemeTest.php
Labels: :factory: Back-End

#3057 New Crowdin updates
  resources/lang/et/auth.php
  resources/lang/it/auth.php
  resources/lang/it/common.php
  resources/lang/it/entities.php
  resources/lang/ru/auth.php
  resources/lang/ru/common.php
  resources/lang/ru/entities.php
  resources/lang/ru/errors.php
  resources/lang/ru/settings.php
  resources/lang/zh_CN/activities.php
  resources/lang/zh_CN/auth.php
  resources/lang/zh_CN/common.php
  resources/lang/zh_CN/entities.php
  resources/lang/zh_CN/settings.php
Labels: :earth_africa: Translations

#3076 New Crowdin updates
  resources/lang/pt_BR/settings.php
  resources/lang/pt_BR/validation.php
  resources/lang/tr/auth.php
  resources/lang/zh_CN/common.php
  resources/lang/zh_CN/entities.php
  resources/lang/zh_CN/settings.php
Labels: :earth_africa: Translations
