Repository BookStackApp/BookStack, pull requests merged in 2021-03, with the labels that each got.

#2618 New Crowdin updates
  resources/lang/ar/settings.php
  resources/lang/bg/settings.php
  resources/lang/bs/settings.php
  resources/lang/cs/settings.php
  resources/lang/da/settings.php
  resources/lang/de/settings.php
  resources/lang/de_informal/common.php
  resources/lang/de_informal/settings.php
  resources/lang/es/settings.php
  resources/lang/es_AR/common.php
  resources/lang/es_AR/settings.php
  resources/lang/fa/settings.php
  resources/lang/fr/settings.php
  resources/lang/he/settings.php
  resources/lang/hu/settings.php
  resources/lang/id/settings.php
  resources/lang/it/settings.php
  resources/lang/ja/settings.php
  resources/lang/ko/settings.php
  resources/lang/lv/settings.php
  resources/lang/nb/settings.php
  resources/lang/nl/settings.php
  resources/lang/pl/settings.php
  resources/lang/pt/settings.php
  resources/lang/pt_BR/settings.php
  resources/lang/ru/settings.php
  resources/lang/sk/settings.php
  resources/lang/sl/settings.php
  resources/lang/sv/settings.php
  resources/lang/tr/settings.php
  resources/lang/uk/settings.php
  resources/lang/vi/settings.php
  resources/lang/zh_CN/settings.php
  resources/lang/zh_TW/settings.php
Labels: :earth_africa: Translations

#2513 Fix French translations
  resources/lang/fr/activities.php
  resources/lang/fr/entities.php
Labels: :earth_africa: Translations

#2533 Fix German translation string
  resources/lang/de_informal/components.php
Labels: :earth_africa: Translations

#2609 Fixed user invite email subject in spanish translation (#2608)
  resources/lang/es/auth.php
Labels: :earth_africa: Translations

#2536 Add Catalan translation
  app/Config/app.php
  app/Http/Middleware/Localization.php
  resources/lang/ca/activities.php
  resources/lang/ca/auth.php
  resources/lang/ca/common.php
  resources/lang/ca/components.php
  resources/lang/ca/entities.php
  resources/lang/ca/errors.php
  resources/lang/ca/pagination.php
  resources/lang/ca/passwords.php
  resources/lang/ca/settings.php
  resources/lang/ca/validation.php
  resources/lang/en/settings.php
Labels: :earth_africa: Translations

#2620 New Crowdin updates
  resources/lang/ar/settings.php
  resources/lang/bg/settings.php
  resources/lang/bs/settings.php
  resources/lang/ca/auth.php
  resources/lang/ca/entities.php
  resources/lang/ca/settings.php
  resources/lang/cs/settings.php
  resources/lang/da/settings.php
  resources/lang/de/auth.php
  resources/lang/de/settings.php
  resources/lang/de_informal/components.php
  resources/lang/de_informal/settings.php
  resources/lang/es/auth.php
  resources/lang/es/settings.php
  resources/lang/es_AR/settings.php
  resources/lang/fa/settings.php
  resources/lang/fr/activities.php
  resources/lang/fr/entities.php
  resources/lang/fr/settings.php
  resources/lang/he/settings.php
  resources/lang/hu/settings.php
  resources/lang/id/settings.php
  resources/lang/it/settings.php
  resources/lang/ja/settings.php
  resources/lang/ko/settings.php
  resources/lang/lv/settings.php
  resources/lang/nb/settings.php
  resources/lang/nl/settings.php
  resources/lang/pl/settings.php
  resources/lang/pt/settings.php
  resources/lang/pt_BR/settings.php
  resources/lang/ru/settings.php
  resources/lang/sk/settings.php
  resources/lang/sl/settings.php
  resources/lang/sv/settings.php
  resources/lang/tr/settings.php
  resources/lang/uk/settings.php
  resources/lang/vi/settings.php
  resources/lang/zh_CN/settings.php
  resources/lang/zh_TW/settings.php
Labels: :earth_africa: Translations

#2626 User slugs
  app/Auth/Access/SocialAuthService.php
  app/Auth/User.php
  app/Auth/UserRepo.php
  app/Entities/Models/Entity.php
  app/Entities/Tools/SearchRunner.php
  app/Entities/Tools/SlugGenerator.php
  app/Http/Controllers/Auth/SocialController.php
  app/Http/Controllers/SearchController.php
  app/Http/Controllers/UserController.php
  app/Http/Controllers/UserProfileController.php
  app/Interfaces/Sluggable.php
  database/factories/ModelFactory.php
  database/migrations/2021_03_08_215138_add_user_slug.php
  resources/views/common/header.blade.php
  routes/web.php
  tests/Auth/AuthTest.php
  tests/Entity/EntitySearchTest.php
  tests/User/UserProfileTest.php
Labels: :book: Docs Update, :factory: Back-End, :hammer_and_wrench: Enhancement, :lock: Security

#2561 Search owned by me
  app/Entities/Tools/SearchRunner.php
  resources/lang/en/entities.php
  resources/views/search/all.blade.php
  tests/Entity/EntitySearchTest.php
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement

#2515 Sort Books within Shelves
  app/Http/Controllers/BookshelfController.php
  app/Http/Controllers/UserController.php
  resources/views/shelves/show.blade.php
Labels: :factory: Back-End, :hammer_and_wrench: Enhancement
