Repository BookStackApp/BookStack, pull requests merged in 2022-02, with the labels that each got.

#3214 New Crowdin updates
  resources/lang/ar/common.php
  resources/lang/bg/common.php
  resources/lang/bs/common.php
  resources/lang/ca/common.php
  resources/lang/cs/common.php
  resources/lang/da/common.php
  resources/lang/de/common.php
  resources/lang/de_informal/common.php
  resources/lang/es/auth.php
  resources/lang/es/common.php
  resources/lang/es_AR/common.php
  resources/lang/et/auth.php
  resources/lang/et/common.php
  resources/lang/et/entities.php
  resources/lang/fa/common.php
  resources/lang/fr/common.php
  resources/lang/he/common.php
  resources/lang/hr/common.php
  resources/lang/hu/common.php
  resources/lang/id/common.php
  resources/lang/it/common.php
  resources/lang/it/settings.php
  resources/lang/ja/common.php
  resources/lang/ko/common.php
  resources/lang/lt/common.php
  resources/lang/lv/common.php
  resources/lang/nb/common.php
  resources/lang/nl/common.php
  resources/lang/pl/common.php
  resources/lang/pt/common.php
  resources/lang/pt_BR/common.php
  resources/lang/ru/common.php
  resources/lang/sk/common.php
  resources/lang/sl/common.php
  resources/lang/sv/common.php
  resources/lang/tr/common.php
  resources/lang/uk/common.php
  resources/lang/vi/common.php
  resources/lang/zh_CN/common.php
  resources/lang/zh_TW/common.php
Labels: :earth_africa: Translations

#3256 Update Korean translation
  resources/lang/ko/activities.php
  resources/lang/ko/auth.php
  resources/lang/ko/common.php
  resources/lang/ko/components.php
  resources/lang/ko/entities.php
  resources/lang/ko/errors.php
  resources/lang/ko/passwords.php
  resources/lang/ko/settings.php
  resources/lang/ko/validation.php
Labels: :earth_africa: Translations

#3251 New Crowdin updates
  resources/lang/es/validation.php
  resources/lang/he/activities.php
  resources/lang/he/auth.php
  resources/lang/he/common.php
  resources/lang/he/entities.php
  resources/lang/he/errors.php
Labels: :earth_africa: Translations

#3245 Updated minimum php version from 7.3 to 7.4
  .github/workflows/phpstan.yml
  .github/workflows/phpunit.yml
  .github/workflows/test-migrations.yml
  composer.json
  composer.lock
  dev/docker/Dockerfile
Labels: :wrench: Maintenance, :factory: Back-End

#3238 User Management API
  app/Api/ApiDocsGenerator.php
  app/Api/ListingResponseBuilder.php
  app/Auth/Access/Guards/LdapSessionGuard.php
  app/Auth/Access/RegistrationService.php
  app/Auth/Role.php
  app/Auth/User.php
  app/Auth/UserRepo.php
  app/Console/Commands/CreateAdmin.php
  app/Console/Commands/DeleteUsers.php
  app/Exceptions/Handler.php
  app/Exceptions/NotifyException.php
  app/Http/Controllers/Api/ApiController.php
  app/Http/Controllers/Api/UserApiController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/UserController.php
  app/Providers/AuthServiceProvider.php
  dev/api/requests/users-create.json
  dev/api/requests/users-delete.json
  dev/api/requests/users-update.json
  dev/api/responses/users-create.json
  dev/api/responses/users-list.json
  dev/api/responses/users-read.json
  dev/api/responses/users-update.json
  resources/lang/en/activities.php
  resources/lang/en/settings.php
  resources/views/users/parts/language-option-row.blade.php
  routes/api.php
  tests/Api/TestsApi.php
  tests/Api/UsersApiTest.php
  tests/Auth/UserInviteTest.php
  tests/User/UserManagementTest.php
Labels: :hammer_and_wrench: Enhancement, :factory: Back-End, :nut_and_bolt: API Request

#3258 New Crowdin updates
  resources/lang/ar/editor.php
  resources/lang/bg/editor.php
  resources/lang/bs/editor.php
  resources/lang/ca/editor.php
  resources/lang/cs/editor.php
  resources/lang/da/editor.php
  resources/lang/de/editor.php
  resources/lang/de_informal/editor.php
  resources/lang/es/editor.php
  resources/lang/es_AR/editor.php
  resources/lang/et/editor.php
  resources/lang/fa/editor.php
  resources/lang/fr/editor.php
  resources/lang/he/editor.php
  resources/lang/hr/editor.php
  resources/lang/hu/editor.php
  resources/lang/id/editor.php
  resources/lang/it/editor.php
  resources/lang/ja/editor.php
  resources/lang/ko/editor.php
  resources/lang/lt/editor.php
  resources/lang/lv/editor.php
  resources/lang/nb/editor.php
  resources/lang/nl/editor.php
  resources/lang/pl/editor.php
  resources/lang/pt/editor.php
  resources/lang/pt_BR/editor.php
  resources/lang/ru/editor.php
  resources/lang/sk/editor.php
  resources/lang/sl/editor.php
  resources/lang/sv/editor.php
  resources/lang/tr/editor.php
  resources/lang/uk/editor.php
  resources/lang/vi/editor.php
  resources/lang/zh_CN/editor.php
  resources/lang/zh_TW/editor.php
Labels: :earth_africa: Translations

#3260 WYSIWYG details/summary blocks
  app/Entities/Tools/ExportFormatter.php
  resources/js/code.mjs
  resources/js/wysiwyg/config.js
  resources/js/wysiwyg/plugin-codeeditor.js
  resources/js/wysiwyg/plugins-details.js
  resources/lang/en/editor.php
  resources/sass/_pages.scss
  resources/sass/_tinymce.scss
  tests/Entity/ExportTest.php
Labels: :hammer_and_wrench: Enhancement, :computer: Front-End, :memo: WYSIWYG Editor

#3291 New Crowdin updates
  resources/lang/zh_CN/editor.php
Labels: :earth_africa: Translations
