Repository BookStackApp/BookStack, pull requests merged in 2022-01, with the labels that each got.

#3138 Added webhook_call_before logical theme system event hook
  app/Actions/DispatchWebhookJob.php
  app/Theming/ThemeEvents.php
  tests/ThemeTest.php
Labels: :factory: Back-End

#3141 Added page titles to many missing app areas
  app/Http/Controllers/Auth/MfaBackupCodesController.php
  app/Http/Controllers/Auth/MfaController.php
  app/Http/Controllers/Auth/MfaTotpController.php
  app/Http/Controllers/FavouriteController.php
  app/Http/Controllers/PageController.php
  app/Http/Controllers/RoleController.php
  app/Http/Controllers/TagController.php
  app/Http/Controllers/UserProfileController.php
  app/Http/Controllers/WebhookController.php
Labels: :hammer_and_wrench: Enhancement, :massage: UX

#3153 Update auth.php
  resources/lang/es/auth.php
Labels: :earth_africa: Translations

#3148 New Crowdin updates
  resources/lang/cs/common.php
  resources/lang/ja/auth.php
  resources/lang/ja/common.php
  resources/lang/ja/entities.php
  resources/lang/ja/errors.php
  resources/lang/ja/settings.php
  resources/lang/pt_BR/activities.php
  resources/lang/pt_BR/common.php
  resources/lang/zh_CN/common.php
  resources/lang/zh_CN/settings.php
Labels: :earth_africa: Translations

#3193 chore(dev): add xdebug support for docker setup
  dev/docker/Dockerfile
  dev/docker/php/conf.d/xdebug.ini
  docker-compose.yml
  readme.md
Labels: :wrench: Maintenance, :octocat: Admin/Meta

#3177 enh(recently updated): show updatedBy and updated_at
  app/Http/Controllers/PageController.php
  resources/views/entities/list-item.blade.php
Labels: :hammer_and_wrench: Enhancement, :factory: Back-End, :massage: UX

#3179 When creating a user, do not persist the user on invitation sending failure
  app/Http/Controllers/UserController.php
  tests/User/UserManagementTest.php
Labels: :hammer_and_wrench: Enhancement, :factory: Back-End

#3158 New Crowdin updates
  resources/lang/es_AR/activities.php
  resources/lang/es_AR/common.php
  resources/lang/es_AR/entities.php
  resources/lang/es_AR/settings.php
  resources/lang/fa/activities.php
  resources/lang/fa/auth.php
  resources/lang/fa/common.php
  resources/lang/fa/entities.php
  resources/lang/fa/errors.php
  resources/lang/fa/settings.php
  resources/lang/fa/validation.php
  resources/lang/fr/common.php
  resources/lang/fr/settings.php
  resources/lang/ja/common.php
  resources/lang/ja/settings.php
  resources/lang/ru/common.php
  resources/lang/ru/settings.php
  resources/lang/sk/activities.php
Labels: :earth_africa: Translations

#3210 Massively simplify the 503 error view
  resources/views/errors/503.blade.php
Labels: :hammer_and_wrench: Enhancement, :factory: Back-End
