Repository BookStackApp/BookStack, pull requests merged in 2022-07, with the labels that each got.

#3573 M1/Apple Silicon dev docker compatibility
  dev/docker/Dockerfile
Labels: :wrench: Maintenance

#3569 Permissions System Refactor
  app/Actions/ActivityLogger.php
  app/Actions/ActivityQueries.php
  app/Actions/TagRepo.php
  app/Auth/Permissions/JointPermissionBuilder.php
  app/Auth/Permissions/PermissionApplicator.php
  app/Auth/Permissions/PermissionService.php
  app/Auth/Permissions/PermissionsRepo.php
  app/Auth/Permissions/SimpleEntityData.php
  app/Auth/User.php
  app/Config/app.php
  app/Console/Commands/RegeneratePermissions.php
  app/Entities/Models/Bookshelf.php
  app/Entities/Models/Entity.php
  app/Entities/Models/Page.php
  app/Entities/Queries/EntityQuery.php
  app/Entities/Queries/Popular.php
  app/Entities/Queries/RecentlyViewed.php
  app/Entities/Queries/TopFavourites.php
  app/Entities/Tools/SearchRunner.php
  app/Entities/Tools/ShelfContext.php
  app/Facades/Permissions.php
  app/Http/Controllers/BookshelfController.php
  app/Http/Controllers/SearchController.php
  app/Providers/CustomFacadeProvider.php
  app/Uploads/Attachment.php
  app/Uploads/ImageRepo.php
  app/helpers.php
  database/migrations/2022_07_16_170051_drop_joint_permission_type.php
  database/seeders/DummyContentSeeder.php
  database/seeders/LargeContentSeeder.php
  resources/lang/en/entities.php
  resources/sass/_lists.scss
  resources/sass/_variables.scss
  resources/views/chapters/show.blade.php
  resources/views/entities/list-item.blade.php
  resources/views/pages/show.blade.php
  resources/views/search/parts/entity-ajax-list.blade.php
  tests/Api/AttachmentsApiTest.php
  tests/Commands/RegeneratePermissionsCommandTest.php
  tests/Entity/EntitySearchTest.php
  tests/PublicActionTest.php
  tests/SharedTestHelpers.php
Labels: :wrench: Maintenance, :factory: Back-End

#3579 Updated DOMPDF, and other PHP dependancies
  app/Config/app.php
  app/Config/dompdf.php
  app/Entities/Tools/PdfGenerator.php
  composer.json
  composer.lock
  tests/Entity/PageContentTest.php
  tests/Unit/ConfigTest.php
Labels: :wrench: Maintenance, :factory: Back-End

#3591 Improved shelf book management interface
  app/Http/Controllers/BookshelfController.php
  resources/js/components/shelf-sort.js
  resources/lang/en/entities.php
  resources/sass/_forms.scss
  resources/sass/styles.scss
  resources/views/shelves/parts/form.blade.php
Labels: :wrench: Maintenance, :art: Design, :computer: Front-End, :massage: UX

#3593 Code-editor lang favorites system
  app/Http/Controllers/UserController.php
  resources/js/code.mjs
  resources/js/components/code-editor.js
  resources/sass/_components.scss
  resources/views/pages/parts/code-editor.blade.php
  routes/web.php
  tests/User/UserPreferencesTest.php
Labels: :computer: Front-End, :massage: UX

#3598 Added 'Sort Book' action to chapters
  resources/lang/en/entities.php
  resources/views/chapters/show.blade.php
  tests/Entity/ChapterTest.php
Labels: :massage: UX

#3599 Add editor shortcuts for two main list types
  resources/js/components/markdown-editor.js
  resources/js/wysiwyg/config.js
  resources/js/wysiwyg/shortcuts.js
  resources/views/help/wysiwyg.blade.php
Labels: :book: Docs Update, :computer: Front-End, :memo: WYSIWYG Editor, > Markdown Editor

#3556 Fixed comment count update error
  resources/lang/zh_CN/entities.php
  resources/lang/zh_TW/entities.php
Labels: :earth_africa: Translations

#3570 Fixed some typos and corrected grammar.
  resources/lang/de/auth.php
  resources/lang/de/entities.php
  resources/lang/de/errors.php
  resources/lang/de/settings.php
  resources/lang/de/validation.php
  resources/lang/de_informal/auth.php
  resources/lang/de_informal/common.php
  resources/lang/de_informal/entities.php
  resources/lang/de_informal/errors.php
  resources/lang/de_informal/settings.php
  resources/lang/de_informal/validation.php
Labels: :earth_africa: Translations
