Repository BookStackApp/BookStack, pull requests merged in 2022-08, with the labels that each got.

#3605 New Crowdin updates
  resources/lang/pl/common.php
  resources/lang/pl/editor.php
  resources/lang/pl/entities.php
  resources/lang/ru/editor.php
  resources/lang/ru/entities.php
  resources/lang/zh_CN/editor.php
  resources/lang/zh_CN/entities.php
Labels: :earth_africa: Translations

#3625 New Crowdin updates
  resources/lang/nl/entities.php
  resources/lang/pt_BR/activities.php
Labels: :earth_africa: Translations

#3630 Export template partials
  resources/views/layouts/export.blade.php
  resources/views/layouts/parts/export-body-end.blade.php
  resources/views/layouts/parts/export-body-start.blade.php
  tests/ThemeTest.php
Labels: :factory: Back-End, :paintbrush: View Customization, :truck: Export System

#3632 Fixed failed permission checks due to non-loaded fields
  app/Auth/Permissions/PermissionApplicator.php
  app/Entities/Repos/BaseRepo.php
  app/Entities/Repos/BookshelfRepo.php
  app/Entities/Tools/SearchRunner.php
  app/Http/Controllers/FavouriteController.php
  tests/FavouriteTest.php
Labels: :bug: Bug, :factory: Back-End

#3635 New Crowdin updates
  resources/lang/ja/editor.php
  resources/lang/ko/activities.php
  resources/lang/ko/auth.php
  resources/lang/ko/common.php
  resources/lang/ko/editor.php
  resources/lang/ko/entities.php
  resources/lang/ko/errors.php
  resources/lang/ko/settings.php
Labels: :earth_africa: Translations

#3639 Completion of Persian translation 2022-08-10
  resources/lang/fa/activities.php
  resources/lang/fa/common.php
  resources/lang/fa/editor.php
  resources/lang/fa/entities.php
  resources/lang/fa/settings.php
  resources/lang/fa/validation.php
Labels: :earth_africa: Translations

#3616 Added OIDC group sync functionality
  .env.example.complete
  app/Auth/Access/Oidc/OidcOAuthProvider.php
  app/Auth/Access/Oidc/OidcService.php
  app/Config/oidc.php
  tests/Auth/OidcTest.php
Labels: :book: Docs Update, :factory: Back-End, :door: Authentication
