Repository BookStackApp/BookStack, pull requests merged in 2022-06, with the labels that each got.

#3499 Chapter and Book Conversion Actions
  app/Actions/ActivityType.php
  app/Entities/Repos/BookRepo.php
  app/Entities/Repos/BookshelfRepo.php
  app/Entities/Repos/PageRepo.php
  app/Entities/Tools/Cloner.php
  app/Entities/Tools/HierarchyTransformer.php
  app/Entities/Tools/TrashCan.php
  app/Http/Controllers/Api/BookApiController.php
  app/Http/Controllers/Api/BookshelfApiController.php
  app/Http/Controllers/BookController.php
  app/Http/Controllers/BookshelfController.php
  app/Http/Controllers/ChapterController.php
  resources/lang/en/activities.php
  resources/lang/en/entities.php
  resources/views/books/edit.blade.php
  resources/views/books/parts/convert-to-shelf.blade.php
  resources/views/chapters/edit.blade.php
  resources/views/chapters/parts/convert-to-book.blade.php
  routes/web.php
  tests/Api/BooksApiTest.php
  tests/Api/ShelvesApiTest.php
  tests/Entity/BookTest.php
  tests/Entity/ConvertTest.php
  tests/OpenGraphTest.php
  tests/SharedTestHelpers.php
Labels: :hammer_and_wrench: Enhancement, :factory: Back-End

#3512 WYSIWYG Code Editor Updates
  resources/js/code.mjs
  resources/js/components/code-editor.js
  resources/sass/_components.scss
  resources/views/common/confirm-dialog.blade.php
  resources/views/entities/selector-popup.blade.php
  resources/views/pages/parts/code-editor.blade.php
  resources/views/pages/parts/image-manager.blade.php
Labels: :hammer_and_wrench: Enhancement, :art: Design, :massage: UX

#3406 Skip intermediate login page with single provider
  app/Config/auth.php
  app/Http/Controllers/Auth/LoginController.php
  resources/views/auth/login-redirect.blade.php
  tests/Auth/OidcTest.php
Labels: :hammer_and_wrench: Enhancement, :book: Docs Update, :factory: Back-End, :door: Authentication

#3526 New Crowdin updates
  resources/lang/fr/activities.php
  resources/lang/fr/auth.php
  resources/lang/fr/entities.php
  resources/lang/zh_CN/activities.php
  resources/lang/zh_CN/auth.php
  resources/lang/zh_CN/entities.php
Labels: :earth_africa: Translations

#3531 New Crowdin updates
  resources/lang/it/activities.php
  resources/lang/it/auth.php
  resources/lang/it/entities.php
  resources/lang/ja/activities.php
  resources/lang/ja/common.php
  resources/lang/ja/entities.php
  resources/lang/pl/auth.php
  resources/lang/pl/entities.php
  resources/lang/ru/activities.php
  resources/lang/ru/auth.php
  resources/lang/ru/editor.php
  resources/lang/ru/entities.php
  resources/lang/zh_CN/settings.php
Labels: :earth_africa: Translations
