Repository BookStackApp/BookStack, pull requests merged in 2023-06, with the labels that each got.

#4286 Comment threads
  app/Activity/CommentRepo.php
  app/Activity/Controllers/CommentController.php
  app/Activity/Tools/CommentTree.php
  app/Entities/Controllers/PageController.php
  lang/en/entities.php
  resources/js/components/index.js
  resources/js/components/page-comment.js
  resources/js/components/page-comments.js
  resources/sass/_components.scss
  resources/views/comments/comment-branch.blade.php
  resources/views/comments/comment.blade.php
  resources/views/comments/comments.blade.php
  resources/views/comments/create.blade.php
  resources/views/pages/show.blade.php
  tests/Entity/CommentTest.php
Labels: :hammer_and_wrench: Enhancement, :massage: UX

#4322 Added read-only comments listing into page editor
  app/Activity/Controllers/CommentController.php
  app/Entities/Controllers/PageController.php
  app/Entities/Tools/PageEditorData.php
  lang/en/entities.php
  resources/sass/_components.scss
  resources/views/comments/comment.blade.php
  resources/views/comments/comments.blade.php
  resources/views/pages/parts/editor-toolbox.blade.php
  resources/views/pages/parts/toolbox-comments.blade.php
  tests/Entity/CommentTest.php
Labels: :hammer_and_wrench: Enhancement

#4318 Change JsonDebugException to Responsable interface
  app/Exceptions/JsonDebugException.php
Labels: :wrench: Maintenance, :factory: Back-End

#4332 API Docs: Allowed multi-paragraph descriptions
  app/Api/ApiDocsGenerator.php
  app/Entities/Controllers/PageApiController.php
  app/Permissions/ContentPermissionApiController.php
  app/Uploads/Controllers/ImageGalleryApiController.php
  resources/views/api-docs/parts/endpoint.blade.php
  tests/Api/ApiDocsTest.php
Labels: :wrench: Maintenance, :art: Design
