Repository BookStackApp/BookStack, pull requests merged in 2023-04, with the labels that each got.

#4131 Updated translations with latest Crowdin changes
  lang/bg/activities.php
  lang/bg/auth.php
  lang/bg/common.php
  lang/bg/editor.php
  lang/bg/errors.php
  lang/bg/preferences.php
  lang/es_AR/settings.php
  lang/eu/entities.php
  lang/fa/activities.php
  lang/fa/auth.php
  lang/fa/common.php
  lang/fa/editor.php
  lang/fa/entities.php
  lang/fa/preferences.php
  lang/fr/entities.php
  lang/fr/settings.php
  lang/nb/entities.php
  lang/nb/errors.php
  lang/nb/preferences.php
  lang/nb/settings.php
  lang/nb/validation.php
  lang/pl/settings.php
  lang/pt_BR/activities.php
  lang/pt_BR/errors.php
Labels: :earth_africa: Translations

#3617 Upgrade to codemirror 6
  .gitignore
  dev/build/esbuild.js
  package-lock.json
  package.json
  readme.md
  resources/js/code.mjs
  resources/js/code/index.mjs
  resources/js/code/languages.js
  resources/js/code/legacy-modes.mjs
  resources/js/code/setups.js
  resources/js/code/simple-editor-interface.js
  resources/js/code/themes.js
  resources/js/code/views.js
  resources/js/components/code-editor.js
  resources/js/components/markdown-editor.js
  resources/js/components/page-editor.js
  resources/js/components/pointer.js
  resources/js/markdown/actions.js
  resources/js/markdown/codemirror.js
  resources/js/markdown/editor.js
  resources/js/markdown/shortcuts.js
  resources/js/services/clipboard.js
  resources/js/wysiwyg/plugin-codeeditor.js
  resources/sass/_codemirror.scss
  resources/sass/_components.scss
  resources/sass/_forms.scss
  resources/sass/_pages.scss
  resources/sass/_text.scss
  resources/views/pages/parts/markdown-editor.blade.php
  resources/views/pages/parts/pointer.blade.php
Labels: :book: Docs Update, :computer: Front-End, > Markdown Editor

#4191 Fix timestamp in API docs example response
  dev/api/responses/chapters-list.json
Labels: :bug: Bug, :factory: Back-End

#4193 Custom dropzone implementation
  app/Http/Controllers/Images/GalleryImageController.php
  lang/en/components.php
  lang/en/entities.php
  lang/en/errors.php
  package-lock.json
  package.json
  readme.md
  resources/icons/file.svg
  resources/icons/upload.svg
  resources/js/components/attachments.js
  resources/js/components/dropzone.js
  resources/js/components/image-manager.js
  resources/js/services/clipboard.js
  resources/js/services/dom.js
  resources/js/services/http.js
  resources/sass/_components.scss
  resources/sass/_layout.scss
  resources/sass/styles.scss
  resources/views/attachments/manager-edit-form.blade.php
  resources/views/attachments/manager-link-form.blade.php
  resources/views/attachments/manager.blade.php
  resources/views/form/dropzone.blade.php
  resources/views/form/simple-dropzone.blade.php
  resources/views/pages/parts/image-manager-list.blade.php
  resources/views/pages/parts/image-manager.blade.php
  tests/Uploads/ImageTest.php
Labels: :book: Docs Update, :art: Design, :computer: Front-End, :massage: UX

#4192 changed PageContent.php to accept nested includes
  app/Entities/Tools/PageContent.php
Labels: :book: Docs Update, :factory: Back-End

#4204 Adding a video { width: 100%; }
  resources/sass/_pages.scss
Labels: :bug: Bug, :computer: Front-End
