Repository BookStackApp/BookStack, pull requests merged in 2023-12, with the labels that each got.

#4684 Merge V23.10.3 changes into development
  app/Config/app.php
  app/Entities/Repos/PageRepo.php
  app/Entities/Tools/PageContent.php
  app/Uploads/FaviconHandler.php
  app/Uploads/ImageResizer.php
  app/Users/Models/User.php
  tests/Entity/PageContentTest.php
  tests/ThemeTest.php
Labels: :factory: Back-End

#4714 OIDC RP-Initiated logout
  .env.example.complete
  app/Access/Controllers/LoginController.php
  app/Access/Controllers/OidcController.php
  app/Access/Controllers/RegisterController.php
  app/Access/Controllers/SocialController.php
  app/Access/LoginService.php
  app/Access/Oidc/OidcProviderSettings.php
  app/Access/Oidc/OidcService.php
  app/Access/Saml2Service.php
  app/Access/SocialAuthService.php
  app/Access/SocialDriverManager.php
  app/App/Providers/AppServiceProvider.php
  app/Config/oidc.php
  app/Theming/ThemeService.php
  app/Users/Controllers/UserAccountController.php
  app/Users/Controllers/UserController.php
  resources/views/layouts/parts/header-user-menu.blade.php
  routes/web.php
  tests/Auth/OidcTest.php
  tests/DebugViewTest.php
Labels: :book: Docs Update, :factory: Back-End, :door: Authentication

#4467 OIDC: Add RP-initiated logout implementation
  .env.example.complete
  app/Access/Controllers/OidcController.php
  app/Access/Oidc/OidcService.php
  app/Config/oidc.php
  resources/views/layouts/parts/header-user-menu.blade.php
  routes/web.php
Labels: :factory: Back-End, :door: Authentication

#4727 WYSWIYG: Allowed video/embed alignment controls
  resources/js/wysiwyg/config.js
  resources/js/wysiwyg/fixes.js
  resources/sass/_content.scss
  resources/sass/_tinymce.scss
Labels: :hammer_and_wrench: Enhancement, :memo: WYSIWYG Editor

#4728 Design: Updated buttons to be a bit friendlier
  resources/sass/_buttons.scss
Labels: :art: Design
