Repository BookStackApp/BookStack, pull requests merged in 2024-11, with the labels that each got.

#5312 System CLI update
  bookstack-system-cli
Labels: :wrench: Maintenance

#5250 Updated translations with latest Crowdin changes
  lang/ar/auth.php
  lang/cs/common.php
  lang/cs/entities.php
  lang/cs/errors.php
  lang/et/common.php
  lang/et/entities.php
  lang/et/errors.php
  lang/fr/common.php
  lang/fr/entities.php
  lang/fr/errors.php
  lang/he/activities.php
  lang/he/auth.php
  lang/he/common.php
  lang/he/components.php
  lang/he/passwords.php
  lang/he/preferences.php
  lang/he/settings.php
  lang/it/activities.php
  lang/it/auth.php
  lang/it/common.php
  lang/it/components.php
  lang/it/editor.php
  lang/it/entities.php
  lang/it/errors.php
  lang/ja/common.php
  lang/ja/entities.php
  lang/ja/errors.php
  lang/ko/activities.php
  lang/nl/common.php
  lang/nl/entities.php
  lang/nl/errors.php
  lang/nl/settings.php
  lang/pl/auth.php
  lang/pl/common.php
  lang/pl/entities.php
  lang/pl/errors.php
  lang/pt_BR/editor.php
  lang/pt_BR/entities.php
  lang/tk/activities.php
  lang/tk/auth.php
  lang/tk/common.php
  lang/tk/components.php
  lang/tk/editor.php
  lang/tk/entities.php
  lang/tk/errors.php
  lang/tk/notifications.php
  lang/tk/pagination.php
  lang/tk/passwords.php
  lang/tk/preferences.php
  lang/tk/settings.php
  lang/tk/validation.php
  lang/vi/activities.php
  lang/vi/entities.php
Labels: :earth_africa: Translations

#5317 Updated translations with latest Crowdin changes
  lang/cs/activities.php
  lang/cs/entities.php
  lang/uk/common.php
  lang/uk/entities.php
  lang/uk/errors.php
Labels: :earth_africa: Translations

#5337 Improve Oidc userinfo response Content-Type matching
  app/Access/Oidc/OidcUserinfoResponse.php
Labels: :bug: Bug, :factory: Back-End, :door: Authentication

#5331 Updated translations with latest Crowdin changes
  lang/da/activities.php
  lang/da/settings.php
  lang/ka/activities.php
  lang/nn/activities.php
  lang/nn/auth.php
  lang/zh_TW/validation.php
Labels: :earth_africa: Translations
