Repository BookStackApp/BookStack, pull requests merged in 2025-02, with the labels that each got.

#5470 Fix incorrect condition for displaying new books section
  resources/views/books/index.blade.php
Labels: :bug: Bug, :factory: Back-End

#5488 Search index improvements
  app/Search/SearchIndex.php
  app/Search/SearchOptions.php
  app/Search/SearchTextTokenizer.php
  tests/Search/EntitySearchTest.php
  tests/Search/SearchIndexingTest.php
  tests/Search/SearchOptionsTest.php
  tests/Search/SiblingSearchTest.php
Labels: :hammer_and_wrench: Enhancement, :book: Docs Update, :factory: Back-End

#5415 Further Lexical Fixes
  lang/en/editor.php
  resources/icons/editor/color-display.svg
  resources/icons/editor/color-select.svg
  resources/js/wysiwyg/lexical/core/LexicalCommands.ts
  resources/js/wysiwyg/lexical/core/LexicalConstants.ts
  resources/js/wysiwyg/lexical/core/LexicalNode.ts
  resources/js/wysiwyg/lexical/core/LexicalReconciler.ts
  resources/js/wysiwyg/lexical/core/__tests__/utils/index.ts
  resources/js/wysiwyg/lexical/core/index.ts
  resources/js/wysiwyg/lexical/core/nodes/LexicalElementNode.ts
  resources/js/wysiwyg/lexical/core/nodes/LexicalTextNode.ts
  resources/js/wysiwyg/lexical/core/shared/invariant.ts
  resources/js/wysiwyg/lexical/html/index.ts
  resources/js/wysiwyg/lexical/rich-text/LexicalCodeBlockNode.ts
  resources/js/wysiwyg/lexical/rich-text/LexicalMediaNode.ts
  resources/js/wysiwyg/lexical/rich-text/index.ts
  resources/js/wysiwyg/lexical/table/LexicalCaptionNode.ts
  resources/js/wysiwyg/lexical/table/LexicalTableNode.ts
  resources/js/wysiwyg/nodes.ts
  resources/js/wysiwyg/services/__tests__/auto-links.test.ts
  resources/js/wysiwyg/services/auto-links.ts
  resources/js/wysiwyg/testing.md
  resources/js/wysiwyg/todo.md
  resources/js/wysiwyg/ui/defaults/buttons/controls.ts
  resources/js/wysiwyg/ui/defaults/buttons/inline-formats.ts
  resources/js/wysiwyg/ui/defaults/buttons/objects.ts
  resources/js/wysiwyg/ui/defaults/forms/objects.ts
  resources/js/wysiwyg/ui/defaults/forms/tables.ts
  resources/js/wysiwyg/ui/defaults/toolbars.ts
  resources/js/wysiwyg/ui/framework/blocks/color-field.ts
  resources/js/wysiwyg/ui/framework/blocks/color-picker.ts
  resources/js/wysiwyg/ui/framework/blocks/link-field.ts
  resources/js/wysiwyg/ui/framework/core.ts
  resources/js/wysiwyg/ui/framework/forms.ts
  resources/sass/_editor.scss
Labels: :computer: Front-End, :memo: WYSIWYG Editor

#5491 Addressing PHP 8.4 Deprecations
  app/Access/Ldap.php
  app/Access/SocialDriverManager.php
  app/App/helpers.php
  app/Config/exports.php
  app/Entities/Controllers/BookController.php
  app/Entities/Controllers/PageController.php
  app/Entities/Queries/QueryPopular.php
  app/Entities/Repos/RevisionRepo.php
  app/Theming/ThemeService.php
  app/Uploads/ImageRepo.php
  app/Uploads/ImageService.php
  app/Users/Controllers/UserApiController.php
  app/Util/SsrUrlValidator.php
  composer.json
  composer.lock
  dev/docs/logical-theme-system.md
  tests/Entity/PageEditorTest.php
Labels: :wrench: Maintenance, :factory: Back-End
